### ISSUE TITLE
Changing our branching policy 🔀

### ISSUE THREAD

**Issue by michel-steuwer** [rise-lang/doc#1]
I would like to suggest changing our branching policy :twisted_rightwards_arrows:

We have, so far, worked with a `master` and `development` branch in the [rise](https://github.com/rise-lang/rise) and [shine](https://github.com/rise-lang/shine) repos.

I would suggest that we remove the `development` branch and only operate with a single branch for our continues development.

We should enforce a policy where the `master` branch must always pass all tests (and we should use GitHub actions for enforcing this).

We can use tags and [GitHub releases](https://help.github.com/en/github/administering-a-repository/creating-releases) to highlight particularly stable versions. This change will reflect that our `master` branch always tracks our latest development and there would be no need for a separate `development` branch.

Opinions? :thinking:

**Comment by bastian-koepcke** [comment]
I second this!

**Comment by michel-steuwer** [comment]
I have now deleted :boom: the `development` branches in the `rise` and `shine` repos.

`master` is the way forward :arrow_upper_right:
